### ISSUE TITLE
What are the "hard settings" that need to be changed?

### ISSUE THREAD

**Issue by nospam2k** [bp2008/HdmiExtender#1]

**Comment by bp2008** [comment]
See line 23 of https://github.com/bp2008/HdmiExtender/blob/master/HdmiExtender/HdmiExtenderService/Program.cs

**Comment by bp2008** [comment]
Likewise line 40 of https://github.com/bp2008/HdmiExtender/blob/master/HdmiExtender/HdmiExtenderTest/MainForm.cs

**Comment by nospam2k** [comment]
Ok, so just the nw addresses. Thx for the quick response! I'm trying to get this to work with what I think might be a later model. The Upgrade firmware page says:  Current App Version[Rx_v109_D603_ITE_152MHz7s_IR38_BT_UART_KM_Jun 8 2015_15:49:56] for the receiver and Current App Version[Tx_v109_D603_ITE_152MHz7s_IR38_BT_UART_KM_Jun 8 2015_15:15:47] for the transmit. The labeling seems similar: https://www.amazon.com/gp/product/B01G6ZCQV8/ref=oh_aui_detailpage_o03_s01?ie=UTF8&psc=1

**Comment by bp2008** [comment]
Yes.  You can search the solution for "192.168.168.55" to find anywhere the IP address is hard coded.

Also the network adapter index.  This index is used on line 104 of https://github.com/bp2008/HdmiExtender/blob/master/HdmiExtender/HdmiExtenderLib/HdmiExtenderReceiver.cs  in case you need to debug to inspect LivePacketDevice.AllLocalMachine and figure out which adapter is the one you need to listen with.

**Comment by bp2008** [comment]
That firmware is definitely newer than what I had.

**Comment by nospam2k** [comment]
Yes. I'm struggling. I tried the scripts from danman 1st. I was hoping you might have a later revision. I'm not able to capture the receive init packet. All I see is an arp from the receiver and the next packet is from the transmitter on port 2067: 00:00:00:00:d0:4e:00:00:00:00:00:00:00:00:00:00:00:00:00:00 and then it starts sending packets. The next packet is an JFIF and then just a stream of 1024 byte udp packets on 2068 sent to 226.2.2.2. Not sure if I'm doing anything wrong in capturing, but all packets are UDP and the one ARP. No control packets at all.

I'm using a raspberry pi connected to a switch and connecting the transmit and receive to the same switch to capture.

**Comment by bp2008** [comment]
Alas, I have no idea how your new firmware works.  Probably similar to the previous firmwares, but you might have to figure out how to reconstruct jpegs and audio (if you care about the audio) on your own.

I really abandoned this project 3 years ago in favor of something easier that outputs a standard video stream over http or RTSP.  https://www.aliexpress.com/wholesale?SearchText=hdmi+encoder

**Comment by nospam2k** [comment]
Not wishing to waste your time. If you have a chance. I've put this up on stackoverflow with a single packet capture that I can replay using tcpreplay and I can capture using tcpdump on another machine. I just don't see why I can't use the scripts or your c# to capture the packet.

https://stackoverflow.com/questions/49389659/how-to-capture-a-multicast-packet-programmatically

Thx,

**Comment by bp2008** [comment]
I can't comment on the C or python implementations, but my C# implementation requires WinPCap to be installed, as noted in the main readme.  I imagine there would be runtime errors if you didn't have it though.  The only other thing I can think of is listening on the wrong network adapter.

**Comment by nospam2k** [comment]
Ok, no problem. I finally found some c code that will read the raw packets and am going to compare with the python scripts to see what is different. Thanks for your feedback.

**Comment by bp2008** [comment]
Glad to hear it!  I hope your project goes well!
